### PR TITLE
Add formatter plugin

### PR DESCRIPTION
**Pull request by xstefank**

### CODE REVIEW

**Review by The-Huginn — APPROVED** [review]
LGTM, however don't we want to postpone it until the other PR's are closed? At least #140 as it might be easy to do mistakes rebasing it.

**Comment by xstefank** [comment]
ok, I'll wait for 140

**Comment by The-Huginn** [comment]
can you update & merge this one please @xstefank

**Review by The-Huginn — APPROVED** [review]
LGTM

**Pull request merged**
